[package]
name = "seraphlabs_tokens"
version = "0.1.0"
description = "SeraphLabs token library for starknet smart contract development written in Cairo 1"
# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
seraphlabs_libs = {path = "../libs/"}
seraphlabs_utils = {path = "../utils/"}

[scripts]
test = "cairo-test --filter seraphlabs_tokens --starknet ."
