[package]
name = "seraphlabs_tokens"
version = "0.1.0"
description = "SeraphLabs library for starknet smart contract development written in Cairo 1"
# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
seraphlabs_utils = {path = "../utils/"}